using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ContosoUniversity.Models
{
    public class Course
    {
        // adding attributes into the properties

        //The DatabaseGenerated attribute with the None parameter on the CourseID property 
        //specifies that primary key values are provided by the user rather than generated by the database.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }// CourseID is the primary key

        [Required(ErrorMessage = "Title is required.")]
        [MaxLength(50)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Number of credits is required.")]
        [Range(0, 5, ErrorMessage = "Number of credits must be between 0 and 5.")]
        public int Credits { get; set; }

        [Display(Name = "Department")]
        public int DepartmentID { get; set; }

        // Start Navigation properties Section

        //onr-to-one
        public virtual Department Department { get; set; }
        //one-to-many
        public virtual ICollection<Enrollment> Enrollments { get; set; }//Enrollment is Navigation properties
        public virtual ICollection<Instructor> Instructors { get; set; }

        // End Navigation properties Section
    }
}